version: '2.1'

services:
  oap: 
    image: yangpg9/oap
    networks: [ sw ]
    environment:
      JAVA_OPTS: "-Dmode=no-init -Xms2048m -Xmx2048m" 
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl ch" ]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "12801:12801"      
    depends_on:
      oap-init:
        condition: service_completed_successfully # @feature: cluster; wait for init container to complete
  ui:
    image: yangpg9/ui
    networks: [ sw ]
    ports:
      - "9999:8080"
    depends_on:
      oap:
        condition: service_healthy
    environment:
      SW_OAP_ADDRESS: http://oap:12800 

  oap-init: 
    image: yangpg9/oap
    networks: [ sw ]
    environment:
      JAVA_OPTS: "-Dmode=init" 
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
    networks: [ sw ]
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

networks:
  sw: