version: '2.1'

services:
  oap: 
    image: yangpg9/oap
    networks: [ sw ]
    environment:
      JAVA_OPTS: "-Dmode=no-init -Xms2048m -Xmx2048m" 
      SW_STORAGE: mysql
      SW_JDBC_URL: jdbc:mysql://mysql:3306/swtest?rewriteBatchedStatements=true
      SW_DATA_SOURCE_USER: root
      SW_DATA_SOURCE_PASSWORD: 123456
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl ch" ]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "12801:12801"      
    depends_on:
      oap-init:
        condition: service_completed_successfully # @feature: cluster; wait for init container to complete
  ui:
    image: yangpg9/ui
    networks: [ sw ]
    ports:
      - "9999:8080"
    depends_on:
      oap:
        condition: service_healthy
    environment:
      SW_OAP_ADDRESS: http://oap:12800 

  oap-init: 
    image: yangpg9/oap
    networks: [ sw ]
    environment:
      JAVA_OPTS: "-Dmode=init" 
      SW_STORAGE: mysql
      SW_JDBC_URL: jdbc:mysql://mysql:3306/swtest?rewriteBatchedStatements=true
      SW_DATA_SOURCE_USER: root
      SW_DATA_SOURCE_PASSWORD: 123456      
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0.32
    networks: [ sw ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: swtest
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10     

networks:
  sw: